name = "IOM_NewsDBInteraction"
uuid = "72f181ee-6cc4-400c-98e6-1129de78e134"
authors = ["Connor Smith"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
